services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  seed:
    build:
      context: .
      dockerfile: apps/widget/Dockerfile
    container_name: seed
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017
    depends_on:
      - mongodb
    command: ["npm", "run", "seed"]
    restart: "no"

  express-api:
    build:
      context: .
      dockerfile: apps/widget/Dockerfile
    container_name: express-api
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017
    ports:
      - "3000:3000"
    depends_on:
      - seed

volumes:
  mongodb_data:
